---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: appuio-keycloak-adapter
rules:
- apiGroups:
  - organization.appuio.io
  resources:
  - organizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - organization.appuio.io
  resources:
  - organizations/finalizers
  verbs:
  - update
- apiGroups:
  - organization.appuio.io
  resources:
  - organizations/status
  verbs:
  - get
  - patch
  - update
