---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: appuio-keycloak-adapter
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - appuio.io
  resources:
  - organizationmembers
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appuio.io
  resources:
  - organizationmembers/finalizers
  verbs:
  - update
- apiGroups:
  - appuio.io
  resources:
  - organizationmembers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - appuio.io
  resources:
  - teams
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appuio.io
  resources:
  - teams/finalizers
  verbs:
  - update
- apiGroups:
  - appuio.io
  resources:
  - teams/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - appuio.io
  resources:
  - users
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appuio.io
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - organization.appuio.io
  - rbac.appuio.io
  resources:
  - organizations
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - organization.appuio.io
  - rbac.appuio.io
  resources:
  - organizations/finalizers
  verbs:
  - update
- apiGroups:
  - organization.appuio.io
  - rbac.appuio.io
  resources:
  - organizations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - subjects
  verbs:
  - '*'
